<a href="https://colab.research.google.com/github/vishalkarur08/Introduction-to-python-/blob/main/intro_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Conditional Statements

In [3]:
x = 10
y = 12
# if x is greater than y
if x > y:
  print ("x > y")
# if x is lesser than y
elif x < y:
  print ("x < y")
else:
  print ("x = y")

x < y


In [4]:
numbers = range(1, 6)


In [5]:
numbers

range(1, 6)

In [6]:
for i in numbers:
  print(i)

1
2
3
4
5


In [8]:
# Initialize the value of 1
i = 1
# check the value of i to check if the loop will be continued or not
while i < 5:
  print(i)
# Increment the value of i.
  i = i+1
# print after the value of i
print("Done")

1
2
3
4
Done


FUNCTIONS

In [10]:
def addelements(a,b):
  return(a+b)

In [11]:
result = addelements(3,5)

In [12]:
result

8

In [13]:
addelements(8.09,3.45)


11.54

In [14]:
addelements("hello","world")

'helloworld'

working with collections (LIST, TUPLES, SET, DICTIONARY)

In [15]:
batsmen = ['Rohit', 'Dhawan', 'Kohli', 'Rahane', 'Rayudu', 'Dhoni']
batsmen[0]

'Rohit'

In [16]:
type(batsmen)

list

In [18]:
## Slicing a list
batsmen[0:2]

['Rohit', 'Dhawan']

In [19]:
bowlers = ['Bumrah', 'Sham', 'Bhuvi', 'Kuldeep', 'Chahal']
all_players = batsmen + bowlers
all_players

['Rohit',
 'Dhawan',
 'Kohli',
 'Rahane',
 'Rayudu',
 'Dhoni',
 'Bumrah',
 'Sham',
 'Bhuvi',
 'Kuldeep',
 'Chahal']

In [21]:
all_players.index('Dhoni')

5

In [22]:
all_players.reverse()
all_players

['Chahal',
 'Kuldeep',
 'Bhuvi',
 'Sham',
 'Bumrah',
 'Dhoni',
 'Rayudu',
 'Rahane',
 'Kohli',
 'Dhawan',
 'Rohit']

tuples

In [23]:
odiDebut = ('Kohli', 2008)
odiDebut

('Kohli', 2008)

In [24]:
odiDebut[0]

'Kohli'

In [25]:
players = tuple(all_players)
players

('Chahal',
 'Kuldeep',
 'Bhuvi',
 'Sham',
 'Bumrah',
 'Dhoni',
 'Rayudu',
 'Rahane',
 'Kohli',
 'Dhawan',
 'Rohit')

SETS

In [27]:
wc2011 = {"Dhoni", "Sehwag", "Tendulkar", "Gambhir",
"Kohli", "Raina", "Yuvraj", "Yusuf"}
wc2015 = {"Dhoni", "Dhawan", "Rohit", "Rahane",
"Kohli", "Raina", "Rayudu", "Jadeja"}

In [ ]:
#To find the list of all batsmen who played in either 2011 or 2015 world cup, we can take union of the above two sets.

In [28]:
wc2011.union(wc2015)

{'Dhawan',
 'Dhoni',
 'Gambhir',
 'Jadeja',
 'Kohli',
 'Rahane',
 'Raina',
 'Rayudu',
 'Rohit',
 'Sehwag',
 'Tendulkar',
 'Yusuf',
 'Yuvraj'}

In [29]:
#To find the list of all batsmen who played for both 2011 and 2015 world cup, we can take intersection of these two sets wc2011 and wc2015.
wc2011.intersection(wc2015)

{'Dhoni', 'Kohli', 'Raina'}

In [30]:
#If we need to find the new batsmen who were not part of 2011 world cup and played in 2015 world cup, we take difference of wc2015 from wc2011.
wc2015.difference( wc2011 )

{'Dhawan', 'Jadeja', 'Rahane', 'Rayudu', 'Rohit'}

Dictionary

In [32]:
wcWinners = {1975: "West Indies",
  1979: "West Indies",
  1983: "India",
  1987: "Australia",
  1991: "Pakistan",
  1996: "Sri Lanka",
  1999: "Australia",
  2003: "Australia",
  2007: "Australia",
  2011: "India"}

In [33]:
wcWinners[1983]


'India'

In [34]:
#For a list of all winning countries use the following code:
wcWinners.values()

dict_values(['West Indies', 'West Indies', 'India', 'Australia', 'Pakistan', 'Sri Lanka', 'Australia', 'Australia', 'Australia', 'India'])

In [35]:
set(wcWinners.values())

{'Australia', 'India', 'Pakistan', 'Sri Lanka', 'West Indies'}

In [37]:
#To adding a new key-value pair to the dictionary, use the following code:
wcWinners[2015] = 'Australia'
wcWinners

{1975: 'West Indies',
 1979: 'West Indies',
 1983: 'India',
 1987: 'Australia',
 1991: 'Pakistan',
 1996: 'Sri Lanka',
 1999: 'Australia',
 2003: 'Australia',
 2007: 'Australia',
 2011: 'India',
 2015: 'Australia'}

NUMPY

In [38]:
import numpy as np

In [39]:
a = np.array([1,2,3,4,5])

In [40]:
type(a)

numpy.ndarray

In [41]:
a.shape

(5,)

In [42]:
a.size

5

In [43]:
b = np.array([[1,2,3,4],[4,5,6,7]])

In [44]:
type(b)

numpy.ndarray

In [45]:
b.shape

(2, 4)

In [46]:
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [47]:
b.size

8

In [48]:
b[0]

array([1, 2, 3, 4])

In [49]:
b[0][0]

np.int64(1)

In [50]:
b[1][2]

np.int64(6)

In [51]:
b[0][3]

np.int64(4)

In [52]:
c = b.reshape(4,2)

In [53]:
c

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [55]:
print(a.sum())
print(a)

15
[1 2 3 4 5]


In [56]:
a.prod() #multiplication

np.int64(120)

In [57]:
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [58]:
b.sum(axis=0) #its going to take the sum row wise

array([ 5,  7,  9, 11])

In [59]:
b.sum(axis=1) #its going to take the sum column wise i.e column wise addition

array([10, 22])

In [60]:
# Dot product of two arrays
# Note: For dot product, the inner dimensions of the arrays must match.
# Reshape 'b' to match the dimensions for dot product with 'a'
b_reshaped = b.reshape(4, 2)
# Since 'a' is 1D (5,), we can't directly take the dot product with b_reshaped (4,2).
# Let's create a new array for demonstration purposes that can be used for dot product with 'a'.
# We'll create a 2D array where the number of columns matches the size of 'a'.
c = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
dot_product_result = a.dot(c.T) # Using the transpose of c for compatible dimensions
print("Dot product of a and c.T:", dot_product_result)

# Element-wise multiplication
element_wise_multiplication = a * a
print("Element-wise multiplication of a with itself:", element_wise_multiplication)

# Element-wise multiplication of array 'b' with itself
element_wise_multiplication_b = b * b
print("Element-wise multiplication of b with itself:", element_wise_multiplication_b)

Dot product of a and c.T: [ 55 130]
Element-wise multiplication of a with itself: [ 1  4  9 16 25]
Element-wise multiplication of b with itself: [[ 1  4  9 16]
 [16 25 36 49]]
